spring:
  application:
    name: medicare
  datasource:
    url: jdbc:postgresql://localhost:5432/medicare
    driver-class-name: org.postgresql.Driver
    username: app
    password: telus
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: abmsg.tsl.telus.com
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
